version: "3.7"
services:
  db:
    image: mariadb:10.6.1
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=utRgB9m5sd2MTnKy5K5GWEvpnrttx9RD
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 33060:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080