version: "3.7"
services:
  webapp:
    build: ./webapp
    restart: always
    ports:
      - "80:80"
    working_dir: /webapp

  backend:
    build: ./

  db:
    image: mariadb:10.6.1
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=utRgB9m5sd2MTnKy5K5GWEvpnrttx9RD
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306